### ISSUE TITLE
Banners Designs

### ISSUE THREAD

**Issue by nathanmurdock** [stephenhenderson808/musicianstoolkit#105]
@createoutloud We also need to design some new banners with our new "Music Your Way" logo and theme. We need to have them ready for us in time for the Love Loud Festival. We'll of course use them for future events and shows as well. 

1. - [ ] A branded tent:
https://www.vispronet.com/pop-up-tent-basic-10x10-walls?gclid=EAIaIQobChMIxpCQt_-91QIViG5-Ch25cQNYEAYYAiABEgLd1PD_BwE

2. - [ ] Ion Banner (2):
![img_8625](https://user-images.githubusercontent.com/26153511/28977726-7e7e17d4-7900-11e7-91af-249391762e7c.JPG)
We need a new **Ion** banner design (I've attached the template) as well as a **9'x1' design** for our tent we'll have there.

We also need these done as soon as you can as well, so let me know when you think you think you can get the designs over.

[Ion-banner-7'-template.pdf](https://github.com/stephenhenderson808/musicianstoolkit/files/1198818/Ion-banner-7.-template.pdf)

Here are the new logo assets to play with:
![mtlogo_smalltype_black](https://user-images.githubusercontent.com/28458023/28947647-3803395c-786e-11e7-83d4-f3b9757fd3f1.png)
![mtlogo_stacked_black](https://user-images.githubusercontent.com/28458023/28947645-3802f5dc-786e-11e7-8b52-be0ab296e115.png)
![mtlogo_type_black](https://user-images.githubusercontent.com/28458023/28947646-3803255c-786e-11e7-809b-7cbd74db3e6b.png)

**Comment by stephenhenderson808** [comment]
@createoutloud Hey bro! Here are the design files we need to design on for the branded tent. We need them as soon as possible as the turn around time is hefty. 

[Pop-Up-Tent-Deluxe-Wall-with-Full-Print_10.0ftx6.5ft_SS_R1.PDF](https://github.com/stephenhenderson808/musicianstoolkit/files/1209842/Pop-Up-Tent-Deluxe-Wall-with-Full-Print_10.0ftx6.5ft_SS_R1.PDF)
[Pop-Up-Tent-Basic_Full-Print_10.0ftx10.0ft_SS_R1.PDF](https://github.com/stephenhenderson808/musicianstoolkit/files/1209840/Pop-Up-Tent-Basic_Full-Print_10.0ftx10.0ft_SS_R1.PDF)
[Pop-Up-Tent-Deluxe-Half-Wall-with-Full-Print_10.0ftx2.7ft_SS_R1.PDF](https://github.com/stephenhenderson808/musicianstoolkit/files/1209841/Pop-Up-Tent-Deluxe-Half-Wall-with-Full-Print_10.0ftx2.7ft_SS_R1.PDF)

This is what we are looking to get, but I'll leave it to you brother.
<img width="520" alt="screen shot 2017-08-08 at 5 42 56 pm" src="https://user-images.githubusercontent.com/26153511/29099198-0a31dafa-7c61-11e7-8d7e-353b9603a541.png">

**Comment by createoutloud** [comment]
Knocking these out right now.

**Comment by stephenhenderson808** [comment]
@createoutloud Roger. Thank you SO much. Just fyi, We don't need to make it all black. Joseph wants the tent to be white and wants to play around with the walls having some of our photo imagery from the site as well. I'll leave it up to you bro.

**Comment by createoutloud** [comment]
Oh snap. I was taking the mockup literal.

**Comment by createoutloud** [comment]
I also didnt notice a table cloth in the mockups. Did you guys need that still?

**Comment by stephenhenderson808** [comment]
My bad. So this is more like how Joseph wanted it. (Except the top of the tent is white with a black logo instead of black with a white logo.) @createoutloud 
<img width="682" alt="screen shot 2017-08-09 at 12 34 11 pm" src="https://user-images.githubusercontent.com/26153511/29137943-40fde44a-7cff-11e7-99a5-2977fad3e427.png">

**Comment by createoutloud** [comment]
Roger that [thumbs up emoji]

**Comment by stephenhenderson808** [comment]
If you could do a mockup for the table that would be amazing! @createoutloud 
[8_Feet_4-Sided Fitted Table Cover_154 X 88_CFM.pdf](https://github.com/stephenhenderson808/musicianstoolkit/files/1212498/8_Feet_4-Sided.Fitted.Table.Cover_154.X.88_CFM.pdf)

**Comment by stephenhenderson808** [comment]
Is it just me or does the black top look better? @createoutloud

**Comment by createoutloud** [comment]
[Booth1.zip](https://github.com/stephenhenderson808/musicianstoolkit/files/1212619/Booth1.zip)

**Comment by createoutloud** [comment]
Here's a couple files to review. Sorry I'm kind of speeding through these. I'm feeling more pressure for these to be good and done than to to be creative so I'm kind of speeding through them to get back to other tasks.

**Comment by createoutloud** [comment]
I included to table layouts. One is black and one is half and half that you can switch what side is front facing as needed.

**Comment by stephenhenderson808** [comment]
Roger that. Thank you so much!

**Comment by createoutloud** [comment]
because this file has an image on it it's larger so I uploaded it to my CC Cloud: https://adobe.ly/2vQb2R1

**Comment by stephenhenderson808** [comment]
Could you send me the psds for these? Thank you so much. My apologies for the rush!!!!

**Comment by createoutloud** [comment]
They are all illustrator files so open the pdf's in .AI

**Comment by createoutloud** [comment]
No apologies on the rush. Just trying to stick to the timelines.
