### ISSUE TITLE
Design New Course and Lesson View

### ISSUE THREAD

**Issue by stephenhenderson808** [stephenhenderson808/musicianstoolkit#106]
Course Page
- [ ] Better way to show where they are in the course (highlight within chapter view and title the arrows on each side of the video player)
- [ ] For non-users make sure there is a Start Free Trial CTA in the main player
- [ ] Create a way for non-signed in users to intuitively see what is or isn't free and click to sign up pop-up and page if they want to view a locked course.

Make chapter view more intuitive and interesting: 
- [ ] Each lesson gets description in the bar
- [ ] Amount of Time the lesson will take
- [ ] Free or Locked Icon
- [ ] Some kind of highlight if it is being viewed currently
- [ ] Status (Finished, Unfinished, Not Started) (Only for users)
- [ ] Action (Rewatch/Retake, Resume, Start) (Only for users)
- [ ] An icon on the left side of the lesson that shows if it's a video or a quiz

All action for lesson happening on course page:
- [ ] When a lesson is being watched, we need the pdf download for that to show up below the screen, just above the lesson description

These are the instructions for the developers:
<img width="693" alt="screen shot 2017-08-29 at 1 11 28 pm" src="https://user-images.githubusercontent.com/26153511/29877428-d4aa7074-8d5c-11e7-8ec4-41341d9f08ad.png">
<img width="689" alt="screen shot 2017-08-29 at 1 34 52 pm" src="https://user-images.githubusercontent.com/26153511/29877430-d4eb9f40-8d5c-11e7-8e45-4efaade1dc34.png">

Here is some inspiration:
https://laracasts.com/series/git-me-some-version-control
https://scotch.io/courses/getting-started-with-angular-2/user-profile-component
https://www.pluralsight.com/courses/getting-started-modeling-fusion-360-2271

**Comment by stephenhenderson808** [comment]
@createoutloud hey bro! I made a few sketches so you could have a little more gathered visual of what we've been thinking through. Let me know if you have any questions bro!!

**FOR NON USERS COURSE VIEW**
![img_8864](https://user-images.githubusercontent.com/26153511/29882888-b739e2a4-8d6b-11e7-86b2-02abc01bfe86.JPG)

**FOR USERS COURSE/LESSON VIEW**
![img_8863](https://user-images.githubusercontent.com/26153511/29882910-cc4ee108-8d6b-11e7-9fa6-4aa58368165b.JPG)

**Comment by createoutloud** [comment]
Right on. Thank you!

**Comment by createoutloud** [comment]
[NON-USERS-COURSE-VIEW.zip](https://github.com/stephenhenderson808/musicianstoolkit/files/1266310/NON-USERS-COURSE-VIEW.zip)

**Comment by createoutloud** [comment]
Time got away from me today. Got this view done and a lot of this I can carry over to the lesson view. I'll try and get that done today as well. Hit me with any changes you want to make to this or things you feel I'm missing. I'll be up at HQ meeting with Ryan and James so hopefully we can talk story a bit before the day wraps up.

**Comment by stephenhenderson808** [comment]
Yessai Bro!! LOVE this!!

**Comment by createoutloud** [comment]
Let me know if this will work bro. 

[USERS-LESSON-VIEW.zip](https://github.com/stephenhenderson808/musicianstoolkit/files/1269540/USERS-LESSON-VIEW.zip)
