### ISSUE TITLE
Design New Personal Sign Up Page

### ISSUE THREAD

**Issue by stephenhenderson808** [stephenhenderson808/musicianstoolkit#114]
Basic premise is that we like what we have already, it just needs some additions to make it convert the customer easier, more like an optimized landing page:
- [ ] Include Testimonials super close to the top
- [ ] Maybe Include Small Video
- [ ] Include Universal Value Propositions below
- 100+ Video Courses/1500+ Videos
- Learn Any Instrument
- Explore Every Music Career Path
- Industry and Music Education Experts
- Track Learning with Real Metrics
- [ ] Include an FAQ section
- [ ] Include everything in current sign up page

**Comment by createoutloud** [comment]
![landing-page](https://user-images.githubusercontent.com/30101612/30953400-f7605bcc-a3e8-11e7-8eec-8b4e6b1260af.jpg)
![landing-page2](https://user-images.githubusercontent.com/30101612/30953399-f745142a-a3e8-11e7-9779-ce5d8ce86aa1.jpg)

**Comment by createoutloud** [comment]
Bro, super sorry how disconnected I've been the last few weeks adjusting to the new work flow. I need to review these notes again but I did have this idea cooking for a new landing page that i wanted to send over. I'll check back on this tomorrow/today though and refresh my memory on the request.

**Comment by createoutloud** [comment]
My idea on these came from how Vimeo has their sign up page. I was thinking getting them signed up might be more important than getting their payment info right away. I'll do another version with the credit card info but wanted to put this out there. Feels less salesy and more common practice. This way if most users sign up and then bounce at least we have their contact and can maybe contact them to see if we can get more clarity/feedback. Anyways, just some context to these ideas.

**Comment by stephenhenderson808** [comment]
@createoutloud Roger that bro. I love these designs. I incorporated the feel into a cohesive design draft because we still need to preserve the plan functionality and the banner message. I attached it here (SUPER ROUGH) so you can sort of see what we need and make it look pro in a way only you can do. So stoked for these. The dev team starts their sprint redesigning this on monday and begins estimating story points tomorrow, so if you can try get the this one done as soon as can that would be amazing. You rock brother.

![newsignuppagedraft](https://user-images.githubusercontent.com/26153511/30993365-ee7b35f8-a46b-11e7-82f9-377750f1ce12.png)
[NewSignUpPageDraft.psd.zip](https://github.com/stephenhenderson808/musicianstoolkit/files/1342593/NewSignUpPageDraft.psd.zip)

**Comment by createoutloud** [comment]
Right on bro. Yup, I'll get this to you by the morning for sure. 

As always, my thoughts are just ideas bro, I respect your position so I hope you never feel like I'm stepping on your toes. I'm being led by you and only here to support. Much love brother. Ping you back before I get to bed with a more refined version of what you sent me and any changes are needed I'll make it my number 1 priority tomorrow. Thanks bro!

**Comment by stephenhenderson808** [comment]
Roger that! Oh man, I love your ideas and couldn't be more stoked for all you do brother. Have never once felt like my toes were being stepped on haha. You da man.

**Comment by createoutloud** [comment]
Right on. Just want to make sure I shared that with you bro. Much respect.

**Comment by createoutloud** [comment]
Here you go bro. 
![landing-page3](https://user-images.githubusercontent.com/30101612/31008518-aa9c717a-a4c1-11e7-886a-c00475e00b66.jpg)
[Landing-Page3.psd.zip](https://github.com/stephenhenderson808/musicianstoolkit/files/1343729/Landing-Page3.psd.zip)

**Comment by stephenhenderson808** [comment]
CHEEE!! Malo!
