### ISSUE TITLE
Split Screen

### ISSUE THREAD

**Issue by createoutloud** [stephenhenderson808/musicianstoolkit#121]
Hey guys Let me know if this is what you were shooting for with the keynote you sent me. 

[Splitscreens.zip](https://github.com/stephenhenderson808/musicianstoolkit/files/1389209/Splitscreens.zip)

**Comment by nathanmurdock** [comment]
@createoutloud perfect, these look great! I did add a white line on the "Split-Screen" design in between the two pictures to make it a bit easier to separate the Pro and Ed side, but other than that they look good to me. I'll forward these to Joseph and Felipe for development.

**Comment by createoutloud** [comment]
Nice. Sounds great!
