### ISSUE TITLE
Account Setup Meter on Toolkit Homepage

### ISSUE THREAD

**Issue by stephenhenderson808** [stephenhenderson808/musicianstoolkit#43]
We need a graphical way to on the hometab for the user to know their progress in finishing the 'setup' (Confirm Email, Complete Profile, Take On-boarding Survey, Watch Tutorial). It can be a meter, line or anything but it should be prominent on the home tab page until they are finished.

It will show up on the 'Home' tab on the top part (near the welcome image):
![home3](https://user-images.githubusercontent.com/26153511/28140738-d01bae90-6716-11e7-9692-4738c2f4907e.jpg)

Here is some inspiration for the meter:
<img width="1168" alt="screen shot 2017-05-26 at 3 03 33 pm" src="https://user-images.githubusercontent.com/26153511/28140764-e7222614-6716-11e7-93db-4be507e5fd84.png">
<img width="372" alt="screen shot 2017-05-26 at 3 04 02 pm" src="https://user-images.githubusercontent.com/26153511/28140765-e7242662-6716-11e7-8365-4875b5675d8c.png">

**Comment by createoutloud** [comment]
[HOME-meter.zip](https://github.com/stephenhenderson808/musicianstoolkit/files/1164991/HOME-meter.zip)

**Comment by createoutloud** [comment]
My thoughts with this, if you like the position, is that once they complete all the tasks...and close our a session/browser. The next time they log on this section disappears. 

Let me know if you'd like to see this idea in a different spot.
