### ISSUE TITLE
Loading icon

### ISSUE THREAD

**Issue by stephenhenderson808** [stephenhenderson808/musicianstoolkit#55]
Animation for anytime loading occurs

**Comment by createoutloud** [comment]
[treble loader.zip](https://github.com/stephenhenderson808/musicianstoolkit/files/1160944/treble.loader.zip)

**Comment by createoutloud** [comment]
[trumpet loader.zip](https://github.com/stephenhenderson808/musicianstoolkit/files/1161052/trumpet.loader.zip)

**Comment by createoutloud** [comment]
Here are two loader ideas. Let me know if these inspire something else you want to see.

**Comment by stephenhenderson808** [comment]
HOLY AMAZING

**Comment by createoutloud** [comment]
Thanks bro!
