### ISSUE TITLE
Jobs Listing Page

### ISSUE THREAD

**Issue by stephenhenderson808** [stephenhenderson808/musicianstoolkit#77]
We need a page that shows job listings from the 'company page' you previously designed.

On the page it will show jobs and the ability to apply via indeed or linked in.

**Comment by createoutloud** [comment]
[Jobs.zip](https://github.com/stephenhenderson808/musicianstoolkit/files/1161190/Jobs.zip)

**Comment by createoutloud** [comment]
Let me know if this is what you had in mind for this.

**Comment by stephenhenderson808** [comment]
This is it! Chee!
