### ISSUE TITLE
Resources Tab Design

### ISSUE THREAD

**Issue by stephenhenderson808** [stephenhenderson808/musicianstoolkit#78]
We need a resources tab that allows us to host and organize everything we don't have in courses in an organized way. Resources like our publications, extra videos, partner sites, ebooks, blog posts, etc.

Here is some inspiration:
![2016-01-08-resource-page-min](https://user-images.githubusercontent.com/26153511/28141399-a4bb8eca-6719-11e7-8d78-82425b7bccc1.jpg)
![business-resources-lp](https://user-images.githubusercontent.com/26153511/28141401-a4c16872-6719-11e7-91ef-12af63db3165.jpg)
![resources-page-design-min](https://user-images.githubusercontent.com/26153511/28141400-a4bdd04a-6719-11e7-8e92-1e62daa8d1aa.jpg)

**Comment by createoutloud** [comment]
[resources.zip](https://github.com/stephenhenderson808/musicianstoolkit/files/1164762/resources.zip)

**Comment by createoutloud** [comment]
Here's my go at this page bro.

**Comment by stephenhenderson808** [comment]
This is awesome bro. I'll add in the categories. Love the design template and think its perfect.
