### ISSUE TITLE
Homepage logo animation

### ISSUE THREAD

**Issue by stephenhenderson808** [stephenhenderson808/musicianstoolkit#79]
On the homepage in the hero banner we want that logo to be animated: https://invis.io/WQBP3MUS9#/233544917_PERSONAL

**Comment by createoutloud** [comment]
![personal-logo](https://user-images.githubusercontent.com/30101612/28293725-d404bef2-6b12-11e7-8247-ccbec6327d2e.gif)

**Comment by createoutloud** [comment]
[PERSONAL-logo.gif.zip](https://github.com/stephenhenderson808/musicianstoolkit/files/1154234/PERSONAL-logo.gif.zip)

**Comment by stephenhenderson808** [comment]
Perfect. @createoutloud
