### ISSUE TITLE
Value Prop Icons for homepage

### ISSUE THREAD

**Issue by stephenhenderson808** [stephenhenderson808/musicianstoolkit#80]
Animation for each of the value prop icons under the intro video https://invis.io/WQBP3MUS9#/233544917_PERSONAL

**Comment by createoutloud** [comment]
[GREATS.gif.zip](https://github.com/stephenhenderson808/musicianstoolkit/files/1166882/GREATS.gif.zip)

**Comment by createoutloud** [comment]
These other two are a little more involved but they are coming.

**Comment by createoutloud** [comment]
[Home-Animations.zip](https://github.com/stephenhenderson808/musicianstoolkit/files/1167091/Home-Animations.zip)

**Comment by createoutloud** [comment]
Here are these 3 animations.

**Comment by createoutloud** [comment]
[Home-Animations.zip](https://github.com/stephenhenderson808/musicianstoolkit/files/1167098/Home-Animations.zip)
