### ISSUE TITLE
Homepage computer screen animations

### ISSUE THREAD

**Issue by stephenhenderson808** [stephenhenderson808/musicianstoolkit#81]
Animation of the computer screens in the parents section: https://invis.io/WQBP3MUS9#/233544917_PERSONAL

**Comment by createoutloud** [comment]
Might not make it to the 10am meeting but today my goal is to get the last two items/animations wrapped up.

**Comment by stephenhenderson808** [comment]
@createoutloud Roger that brother. No problem at all. Stoked for all of the INCREDIBLE work.

**Comment by createoutloud** [comment]
[home-screen-animations.zip](https://github.com/stephenhenderson808/musicianstoolkit/files/1172688/home-screen-animations.zip)

**Comment by createoutloud** [comment]
I feel good about two of these. I want to try one more idea for the signup screen. The idea I have doesn't match with it being more icons than showing a hint of the site like the other two. I'll get that sent over today.

**Comment by stephenhenderson808** [comment]
THESE ARE AMAZING

**Comment by createoutloud** [comment]
[signup2.gif.zip](https://github.com/stephenhenderson808/musicianstoolkit/files/1184793/signup2.gif.zip)

**Comment by createoutloud** [comment]
Here's an update to the sign up screen bro.
