### ISSUE TITLE
Setup page icon

### ISSUE THREAD

**Issue by stephenhenderson808** [stephenhenderson808/musicianstoolkit#82]
Animation for the setup page icon:
https://invis.io/WQBP3MUS9#/235910059_SurveyPageStart_Family

**Comment by createoutloud** [comment]
[Setup-and-GearAnimation.zip](https://github.com/stephenhenderson808/musicianstoolkit/files/1154009/Setup-and-GearAnimation.zip)

**Comment by createoutloud** [comment]
I noticed I didn't have a page designed for this so I did that real quick and then did the animation. let me know if you want to see something different than what I created. I used your invisionpage as inspiration.

**Comment by stephenhenderson808** [comment]
This is perfect! @createoutloud
