### ISSUE TITLE
Quiz answer animations

### ISSUE THREAD

**Issue by stephenhenderson808** [stephenhenderson808/musicianstoolkit#83]
Animation for the quiz answers:
https://invis.io/WQBP3MUS9#/233546055_Quiz_View3

**Comment by createoutloud** [comment]
![quiz-button-correct](https://user-images.githubusercontent.com/30101612/28287779-2a0cfbca-6afa-11e7-9c24-cad6ad262dcb.gif)
![quiz-button-select](https://user-images.githubusercontent.com/30101612/28287778-2a0aeb00-6afa-11e7-8d73-c4e17f34abb2.gif)
![quiz-button-wrong](https://user-images.githubusercontent.com/30101612/28287780-2a13c39c-6afa-11e7-89ee-db5ba2f8a527.gif)
![quiz-buttons-circle](https://user-images.githubusercontent.com/30101612/28287777-2a0a99fc-6afa-11e7-93ff-c689c4b99a63.gif)

**Comment by createoutloud** [comment]
These animate ONCE instead of on a loop. Felt like a loop would be to overkill for these.

**Comment by stephenhenderson808** [comment]
@createoutloud heck yes. Love it
