### ISSUE TITLE
Quiz finish animation

### ISSUE THREAD

**Issue by stephenhenderson808** [stephenhenderson808/musicianstoolkit#84]
Animation for quiz finishing:
https://invis.io/WQBP3MUS9#/233546054_Quiz_View_Complete

**Comment by createoutloud** [comment]
![quiz-thumb](https://user-images.githubusercontent.com/30101612/28251923-f9fb392a-6a44-11e7-831f-892de69b1119.gif)

**Comment by createoutloud** [comment]
Testing the file uploader

**Comment by stephenhenderson808** [comment]
This is awesome @createoutloud !
